# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 13:19
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rzxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzsj', models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u7ec4\u65f6\u95f4')),
                ('bz', models.TextField(max_length=500, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5165\u7ec4\u4fe1\u606f',
                'verbose_name_plural': '\u5165\u7ec4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Sbcj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cjmc', models.CharField(max_length=50, null=True, verbose_name='\u5382\u5bb6\u540d\u79f0')),
                ('szdq', models.CharField(max_length=50, verbose_name='\u6240\u5728\u5730\u533a')),
            ],
            options={
                'verbose_name': '\u5382\u5bb6\u5b57\u5178',
                'verbose_name_plural': '\u5382\u5bb6\u5b57\u5178',
            },
        ),
        migrations.CreateModel(
            name='Sbxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbxh', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('leix', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u5b57\u5178',
                'verbose_name_plural': '\u8bbe\u5907\u5b57\u5178',
            },
        ),
        migrations.CreateModel(
            name='Yyxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymc', models.CharField(max_length=50, verbose_name='\u533b\u9662\u540d\u79f0')),
                ('shengf', models.CharField(max_length=50, verbose_name='\u6240\u5728\u7701\u4efd')),
                ('dengj', models.CharField(max_length=50, verbose_name='\u533b\u9662\u7b49\u7ea7')),
            ],
            options={
                'ordering': ['-yymc', 'dengj'],
                'verbose_name': '\u533b\u9662\u5b57\u5178',
                'verbose_name_plural': '\u533b\u9662\u5b57\u5178',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ\u53f7\u7801')),
                ('mobil', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='rzxx',
            name='sbcj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acc.Sbcj', verbose_name='\u8bbe\u5907\u5382\u5bb6'),
        ),
        migrations.AddField(
            model_name='rzxx',
            name='sbxh',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Acc.Sbxh', verbose_name='\u8bbe\u5907\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='rzxx',
            name='yymc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acc.Yyxx', verbose_name='\u533b\u9662\u540d\u79f0'),
        ),
    ]
