# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0002_auto_20170624_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rzxx',
            options={'verbose_name': '\u5165\u7ec4\u4fe1\u606f', 'verbose_name_plural': '\u5165\u7ec4\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='sbcj',
            options={'verbose_name': '\u5382\u5bb6\u5b57\u5178', 'verbose_name_plural': '\u5382\u5bb6\u5b57\u5178'},
        ),
        migrations.AlterModelOptions(
            name='sbxh',
            options={'verbose_name': '\u8bbe\u5907\u5b57\u5178', 'verbose_name_plural': '\u8bbe\u5907\u5b57\u5178'},
        ),
        migrations.AlterModelOptions(
            name='yyxx',
            options={'verbose_name': '\u533b\u9662\u5b57\u5178', 'verbose_name_plural': '\u533b\u9662\u5b57\u5178'},
        ),
        migrations.AddField(
            model_name='rzxx',
            name='bz',
            field=models.CharField(max_length=150, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
