# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0003_auto_20170625_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzxx',
            name='bz',
            field=models.TextField(max_length=500, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
