# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0005_auto_20170704_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': '\u7528\u6237\u5217\u8868', 'verbose_name_plural': '\u7528\u6237\u5217\u8868'},
        ),
        migrations.AddField(
            model_name='sbxh',
            name='sbdj',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='\u8bbe\u5907\u7b49\u7ea7'),
        ),
        migrations.AddField(
            model_name='sbxh',
            name='sscj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Acc.Sbcj', verbose_name='\u6240\u5c5e\u5382\u5bb6'),
        ),
    ]
