# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0006_auto_20170706_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FooModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='\u7701')),
                ('city', models.CharField(max_length=50, verbose_name='\u5e02')),
                ('area', models.CharField(max_length=50, verbose_name='\u533a')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acc.FileType')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acc.ManagedFile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acc.FileType')),
            ],
        ),
    ]
