# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0007_filetype_foomodel_managedfile_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooModel',
        ),
    ]
