# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acc', '0009_market_security_securitygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='security',
            name='market',
        ),
        migrations.RemoveField(
            model_name='securitygroup',
            name='market',
        ),
        migrations.RemoveField(
            model_name='securitygroup',
            name='securities',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='m_file',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.AlterField(
            model_name='rzxx',
            name='sbcj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acc.Sbcj', verbose_name='\u8bbe\u5907\u5382\u5bb6'),
        ),
        migrations.AlterField(
            model_name='rzxx',
            name='yymc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acc.Yyxx', verbose_name='\u533b\u9662\u540d\u79f0'),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='ManagedFile',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.DeleteModel(
            name='SecurityGroup',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
